-- Seed data gerado a partir do mockDatabase.js

-- Regiões
INSERT INTO regioes (id, nome, confeds) VALUES (1, 'Norte I', 3);
INSERT INTO regioes (id, nome, confeds) VALUES (2, 'Norte II', 2);
INSERT INTO regioes (id, nome, confeds) VALUES (3, 'Nordeste', 19);
INSERT INTO regioes (id, nome, confeds) VALUES (4, 'Sudeste I', 19);
INSERT INTO regioes (id, nome, confeds) VALUES (5, 'Sudeste II', 16);
INSERT INTO regioes (id, nome, confeds) VALUES (6, 'Sul', 5);
INSERT INTO regioes (id, nome, confeds) VALUES (7, 'Centro-Oeste', 11);

-- Confederações
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (1, 'Centro-Oeste', 'Alto Paranaíba', 'SAL', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (2, 'Centro-Oeste', 'Araguaia Tocantins', 'SAT', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (3, 'Centro-Oeste', 'Brasil Central', 'SBC', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (4, 'Centro-Oeste', 'Centro América', 'SCA', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (5, 'Centro-Oeste', 'Mato Grosso do Sul', 'SMS', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (6, 'Centro-Oeste', 'Matogrossense', 'SMT', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (7, 'Centro-Oeste', 'Planalto', 'SPL', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (8, 'Centro-Oeste', 'Sudoeste de Goiás', 'SSG', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (9, 'Centro-Oeste', 'Taguatinga', 'STG', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (10, 'Centro-Oeste', 'Tocantins', 'STO', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (11, 'Centro-Oeste', 'Triângulo Mineiro', 'STM', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (12, 'Nordeste', 'Agreste Sul Pernambuco', 'SAP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (13, 'Nordeste', 'Alagoas-Sergipe', 'SAS', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (14, 'Nordeste', 'Bahia', 'SBA', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (15, 'Nordeste', 'Ceará', 'SDC', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (16, 'Nordeste', 'Cearense Interiorano', 'SCI', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (17, 'Nordeste', 'Central da Bahia', 'SCH', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (18, 'Nordeste', 'Central Pernambuco', 'SCB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (19, 'Nordeste', 'Centro Sul do Maranhão', 'SCM', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (20, 'Nordeste', 'Chapada Diamantina', 'SCD', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (21, 'Nordeste', 'Extremo Sul da Bahia', 'SEB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (22, 'Nordeste', 'Garanhuns', 'SGA', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (23, 'Nordeste', 'Maranhão', 'SMA', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (24, 'Nordeste', 'Noroeste da Bahia', 'SNO', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (25, 'Nordeste', 'Norte do Ceará', 'SNC', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (26, 'Nordeste', 'Paraíba', 'SPB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (27, 'Nordeste', 'Rio Grande do Norte', 'SRN', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (28, 'Nordeste', 'Sergipe', 'SSE', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (29, 'Nordeste', 'Sul da Bahia', 'SIB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (30, 'Nordeste', 'Oeste da Bahia', 'SOB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (31, 'Norte I', 'Acre', 'SAC', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (32, 'Norte I', 'Noroeste do Brasil', 'SNB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (33, 'Norte I', 'Setentrional', 'SST', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (34, 'Norte II', 'Carajás', 'SCJ', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (35, 'Norte II', 'Tropical', 'STP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (36, 'Sudeste I', 'Bauru', 'SBR', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (37, 'Sudeste I', 'Belo Horizonte', 'SBH', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (38, 'Sudeste I', 'Grande ABC', 'SAB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (39, 'Sudeste I', 'Leste de Minas', 'SLM', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (40, 'Sudeste I', 'Leste de São Paulo', 'SLP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (41, 'Sudeste I', 'Limeira', 'SLA', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (42, 'Sudeste I', 'Litoral Paulista', 'SLI', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (43, 'Sudeste I', 'Norte Paulistano', 'SPN', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (44, 'Sudeste I', 'Oeste de Belo Horizonte', 'SOH', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (45, 'Sudeste I', 'Pampulha', 'SPA', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (46, 'Sudeste I', 'Piratininga', 'SPI', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (47, 'Sudeste I', 'Rio Doce', 'SRD', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (48, 'Sudeste I', 'São Paulo', 'SSP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (49, 'Sudeste I', 'Sorocaba', 'SSR', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (50, 'Sudeste I', 'Sudoeste Paulista', 'SDP', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (51, 'Sudeste I', 'Unido', 'SUN', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (52, 'Sudeste I', 'Vale do Aço', 'SVA', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (53, 'Sudeste I', 'Vale do Paraíba', 'SVP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (54, 'Sudeste I', 'Zona da Mata Mineira', 'SZM', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (55, 'Sudeste II', 'Baixada Fluminense', 'SBF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (56, 'Sudeste II', 'Carioca', 'SCR', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (57, 'Sudeste II', 'Central Espiritossantense', 'SCE', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (58, 'Sudeste II', 'Costa do Sol', 'SCS', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (59, 'Sudeste II', 'Duque de Caxias', 'SCX', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (60, 'Sudeste II', 'E.Santo/R.de Janeiro', 'SER', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (61, 'Sudeste II', 'Guanabara', 'SGB', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (62, 'Sudeste II', 'Leste Fluminense', 'SLF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (63, 'Sudeste II', 'Minas Espírito Santo', 'SME', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (64, 'Sudeste II', 'Norte Fluminense', 'SNF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (65, 'Sudeste II', 'Nova Iguaçu', 'SNI', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (66, 'Sudeste II', 'Oeste Fluminense', 'SOF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (67, 'Sudeste II', 'Oeste Rio de Janeiro', 'SOR', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (68, 'Sudeste II', 'Rio de Janeiro', 'SRJ', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (69, 'Sudeste II', 'Serrano Fluminense', 'SRF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (70, 'Sudeste II', 'Sul Fluminense', 'SSF', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (71, 'Sul', 'Curitiba', 'SCT', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (72, 'Sul', 'Integração Catarinense', 'SIC', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (73, 'Sul', 'Norte do Paraná', 'SNP', true);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (74, 'Sul', 'Sul do Brasil', 'SSB', false);
INSERT INTO confederacoes (id, regiao, nome, sigla, ativa) VALUES (75, 'Sul', 'Vale do Tibagi', 'SVT', true);

-- Delegados
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (1, 'Carlos José Casas Furtado', 'Secretário Executivo', 'SINODAL', 'SAC', 'Norte I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (2, 'José Lucio da Silva Palmares', 'Presidente', 'SINODAL', 'SAP', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (3, 'Juselmo Adriano Alves Martins', 'Presidente', 'SINODAL', 'SAL', 'Centro-Oeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (4, 'João Paulo Langsdorff Serafim', 'Presidente', 'SINODAL', 'SAT', 'Centro-Oeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (5, 'Ramon Miranda', 'Presidente', 'SINODAL', 'SBA', 'Nordeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (6, 'Eraldo de Souza Rosa Júnior', 'Presidente', 'SINODAL', 'SBF', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (7, 'Oswaldo Dalmedico', 'Presidente', 'SINODAL', 'SBR', 'Sudeste I', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (8, 'Jessé de Oliveira', 'Presidente', 'SINODAL', 'SBH', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (9, 'Antonio Lopes', 'Presidente', 'SINODAL', 'SBC', 'Centro-Oeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (10, 'Elisvaldo dos Santos de Sousa', 'Presidente', 'SINODAL', 'SCJ', 'Norte II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (11, 'Cleiton Alves de Almeida Junior', 'Presidente', 'SINODAL', 'SDC', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (12, 'Francisco Xavier de Lima', 'Presidente', 'SINODAL', 'SCI', 'Nordeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (13, 'Jessé Rodrigues Santos', 'Presidente', 'SINODAL', 'SCH', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (14, 'Edmar Junior', 'Presidente', 'SINODAL', 'SCE', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (15, 'Leandro Martins da Silva', 'Presidente', 'SINODAL', 'SCB', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (16, 'Zenildo Nogueira Silva', 'Presidente', 'SINODAL', 'SCM', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (17, 'Izaias Alves', 'Secretário Executivo', 'SINODAL', 'SCS', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (18, 'Josinaldo da Silva Ferreira', 'Presidente', 'SINODAL', 'SCT', 'Sul', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (19, 'Alex Marcelo da Silva Leal', 'Presidente', 'SINODAL', 'SCX', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (20, 'Marcio Pereira Reis', 'Presidente', 'SINODAL', 'SER', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (21, 'Valdomiro Lima Xavier', 'Presidente', 'SINODAL', 'SEB', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (22, 'Silvino de Barros Pereira', 'Vice-Presidente', 'SINODAL', 'SGA', 'Nordeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (23, 'Jarbas de Oliveira Camargo', 'Presidente', 'SINODAL', 'SAB', 'Sudeste I', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (24, 'Milton Carlos Melo', 'Presidente', 'SINODAL', 'SGB', 'Sudeste II', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (25, 'Joel Oroni de Andrade', 'Presidente', 'SINODAL', 'SIC', 'Sul', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (26, 'Adenilson Valerio Leite', '1º Secretario', 'SINODAL', 'SLM', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (27, 'Nelson Pereira da Silva', 'Presidente', 'SINODAL', 'SLP', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (28, 'João Fabiano Terra Veloso', 'Presidente', 'SINODAL', 'SLF', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (29, 'Danny Carlos Rodrigues Couto', 'Presidente', 'SINODAL', 'SLI', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (30, 'Luis Fernando Oliveira Mendes', 'Sec. excutivo', 'SINODAL', 'SMA', 'Nordeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (31, 'Claudinet Evangelista Batista Junior', 'Presidente', 'SINODAL', 'SMS', 'Centro-Oeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (32, 'Evandro dos Santos Pereira', 'Presidente', 'SINODAL', 'SMT', 'Centro-Oeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (33, 'Cesar Romero Valente de Freitas', 'Presidente', 'SINODAL', 'SME', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (34, 'Paulo Roberto Rodrigues de Oliveira', 'Presidente', 'SINODAL', 'SNO', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (35, 'Maurício Tadeu da Cruz', 'Vice-Presidente', 'SINODAL', 'SNB', 'Norte I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (36, 'Eneas Alcantara Santos', 'Presidente', 'SINODAL', 'SNC', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (37, 'Marcio Dias Vanderlei', 'Presidente', 'SINODAL', 'SNP', 'Sul', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (38, 'Ismael Ribeiro Morais', 'Primeiro Secretário', 'SINODAL', 'SNF', 'Sudeste II', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (39, 'Oscar de Miranda', 'Presidente', 'SINODAL', 'SPN', 'Sudeste I', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (40, 'Fabio Lima', 'Presidente', 'SINODAL', 'SNI', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (41, 'Edvaldo Gomes de Almeida', 'Presidente', 'SINODAL', 'SOH', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (42, 'Denilson Porto', 'Presidente', 'SINODAL', 'SOF', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (43, 'Antonio Rodrigues de Souza Filho', 'Presidente', 'SINODAL', 'SOR', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (44, 'Hugo Geraldo da Silva', 'Presidente', 'SINODAL', 'SPA', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (45, 'Maxsuel de Lima', 'Presidente', 'SINODAL', 'SPB', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (46, 'Augusto Fernandes', 'Vice-Presidente', 'SINODAL', 'SPI', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (47, 'Nelson Luiz Christ Mussumesci', 'Presidente', 'SINODAL', 'SRJ', 'Sudeste II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (48, 'Mario Roberto Nascimento', 'Presidente', 'SINODAL', 'SRD', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (49, 'Iranildo', 'Presidente', 'SINODAL', 'SRN', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (50, 'Pedro Marcelo Nogueira de Oliveira', 'Presidente', 'SINODAL', 'SSP', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (51, 'Edson Regly', 'Presidente', 'SINODAL', 'SRF', 'Sudeste II', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (52, 'Willian Amorim Alves', 'Presidente', 'SINODAL', 'SST', 'Norte I', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (53, 'Aminadabe Jesse Silva Ferreira Sales', 'Presidente', 'SINODAL', 'SIB', 'Nordeste', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (54, 'Sinval Alves de Souza', 'Presidente', 'SINODAL', 'SSF', 'Sudeste II', false, false);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (55, 'Pedro Gabriel Felipe dos Santos', 'Presidente', 'SINODAL', 'STG', 'Centro-Oeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (56, 'Tássio Gonçalves Baliza', 'Presidente', 'SINODAL', 'STO', 'Centro-Oeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (57, 'Jakson José Gomes de Oliveira', 'Presidente', 'SINODAL', 'STP', 'Norte II', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (58, 'Luciano Aparecido dos santos', 'Sec. executivo', 'SINODAL', 'SUN', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (59, 'Abel Correa Bravim', 'Presidente', 'SINODAL', 'SVA', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (60, 'Rubens Lima Garcia', 'Presidente', 'SINODAL', 'SVP', 'Sudeste I', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (61, 'Didimon de Araújo Coelho', 'Presidente', 'SINODAL', 'SVT', 'Sul', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (62, 'Sandro Martins de Alcântara', 'Presidente', 'SINODAL', 'SCD', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (63, 'Cícero Rodrigo Guimarães Nascimento', 'Presidente', 'SINODAL', 'SOB', 'Nordeste', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (101, 'Luiz Augusto Gonzaga', 'Presidente', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (102, 'Marco Rodrigues de Sousa', 'VP Centro-Oeste', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (103, 'Francisco Martins da Silva', 'VP Nordeste', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (104, 'Jefferson Wuilliam Ribeiro', 'VP Norte I', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (105, 'Moacir de Freitas Heringer', 'VP Norte II', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (106, 'Rewerson Fugikawa de Salles', 'VP Sudeste I', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (107, 'Samuel Ribeiro da Silva', 'VP Sudeste II', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (108, 'Edson Oliveira dos Anjos', 'VP Sul', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (109, 'Adrivanderson Martins Santos', 'Secretário Executivo', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (110, 'Marcelo Luciano da Costa Santos', 'Primeiro Secretário', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (111, 'Saint'' Clair Cidreira Junior', 'Segundo Secretário', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (112, 'Marcus José Gomes Costa', 'Tesoureiro', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (201, 'Izaías Alves', 'Sec. de Ação Social', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (202, 'Denilson Porto', 'Sec. de Com. Integr. e Imprensa', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (203, 'Gustavo Antonaci Souza Gomes', 'Sec. de Tecnol. da Informação', 'CNHP', '-', '-', true, true);
INSERT INTO delegados (id, nome, cargo, tipo, confederacao, regiao, confirmou, presente) VALUES (204, 'Eraldo de Souza Rosa Júnior', 'Sec.de Espiritualidade', 'CNHP', '-', '-', true, true);

-- Entregas (Documentos)
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (1, 'SAL', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (2, 'SAT', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (3, 'SBC', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (4, 'SCA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (5, 'SMS', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (6, 'SMT', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (7, 'SPL', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (8, 'SSG', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (9, 'STG', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (10, 'STO', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (11, 'STM', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (12, 'SAP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (13, 'SAS', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (14, 'SBA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (15, 'SDC', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (16, 'SCI', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (17, 'SCH', 'green', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (18, 'SCB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (19, 'SCM', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (20, 'SCD', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (21, 'SEB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (22, 'SGA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (23, 'SMA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (24, 'SNO', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (25, 'SNC', 'green', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (26, 'SPB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (27, 'SRN', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (28, 'SSE', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (29, 'SIB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (30, 'SOB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (31, 'SAC', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (32, 'SNB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (33, 'SST', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (34, 'SCJ', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (35, 'STP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (36, 'SBR', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (37, 'SBH', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (38, 'SAB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (39, 'SLM', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (40, 'SLP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (41, 'SLA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (42, 'SLI', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (43, 'SPN', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (44, 'SOH', 'green', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (45, 'SPA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (46, 'SPI', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (47, 'SRD', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (48, 'SSP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (49, 'SSR', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (50, 'SDP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (51, 'SUN', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (52, 'SVA', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (53, 'SVP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (54, 'SZM', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (55, 'SBF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (56, 'SCR', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (57, 'SCE', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (58, 'SCS', 'green', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (59, 'SCX', 'green', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (60, 'SER', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (61, 'SGB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (62, 'SLF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (63, 'SME', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (64, 'SNF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (65, 'SNI', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (66, 'SOF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (67, 'SOR', 'red', 'green', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (68, 'SRJ', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (69, 'SRF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (70, 'SSF', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (71, 'SCT', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (72, 'SIC', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (73, 'SNP', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (74, 'SSB', 'red', 'red', 'red', 0, 0, 0);
INSERT INTO entregas (id, confederacao_sigla, rel_ativ, rel_estat, livro_ata, consulta, proposta, hpp) VALUES (75, 'SVT', 'red', 'red', 'red', 0, 0, 0);
